import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Zarif",
      email: "admin@example.com",
      password: bcrypt.hashSync("12345", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Zarif's Batighor",
        logo: "/images/logo1.png",
        description: "best seller",
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: "User",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Harry Potter and the Philosopohers Stone",
      category: "Novel",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Epub",
      rating: 4.5,
      numReviews: 10,
      description: "Interesting novel",
    },
    {
      name: "Witcher",
      category: "Novel",
      image: "/images/p3.jpg",
      price: 220,
      countInStock: 0,
      brand: "Epub",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "C++",
      category: "Programming",
      image: "/images/p4.jpg",
      price: 78,
      countInStock: 15,
      brand: "Epub",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Grokking Algorithms",
      category: "Programming",
      image: "/images/p5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Epub",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Python Programming",
      category: "Programming",
      image: "/images/p6.jpg",
      price: 139,
      countInStock: 12,
      brand: "Epub",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Python Programming",
      category: "Programming",
      image: "/images/p6.jpg",
      price: 139,
      countInStock: 12,
      brand: "Epub",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Effective Java",
      category: "Programming",
      image: "/images/p7.jpg",
      price: 139,
      countInStock: 12,
      brand: "Epub",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Python Tricks",
      category: "Programming",
      image: "/images/p8.jpg",
      price: 139,
      countInStock: 12,
      brand: "Epub",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};
export default data;
